/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculator;

/**
 *
 * @author Ojasva
 */
public class LoginOrSignUp extends javax.swing.JFrame {

    /**
     * Creates new form LoginOrSignUp
     */
    public LoginOrSignUp() {
        initComponents();
    }

    String username;
    String password;
    String email;
    
    public String resetMethod(){
        return "";
    }
    
    public String getUsername(){
        return usernameFieldLogin.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        passwordLogin = new javax.swing.JLabel();
        usernameLogin = new javax.swing.JLabel();
        usernameFieldLogin = new javax.swing.JTextField();
        passwordFieldLogin = new javax.swing.JPasswordField();
        resetButonLogin = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        passwordReg = new javax.swing.JLabel();
        emailReg = new javax.swing.JLabel();
        usernameReg = new javax.swing.JLabel();
        emailFieldReg = new javax.swing.JTextField();
        usernameFieldReg = new javax.swing.JTextField();
        passwordFieldReg = new javax.swing.JPasswordField();
        resetButtonReg = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        orJustUseAsIs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LOGIN", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        passwordLogin.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        passwordLogin.setForeground(new java.awt.Color(255, 255, 255));
        passwordLogin.setText("PASSWORD:");

        usernameLogin.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        usernameLogin.setForeground(new java.awt.Color(255, 255, 255));
        usernameLogin.setText("USERNAME:");

        usernameFieldLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        usernameFieldLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldLoginActionPerformed(evt);
            }
        });

        passwordFieldLogin.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        resetButonLogin.setBackground(new java.awt.Color(51, 51, 51));
        resetButonLogin.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        resetButonLogin.setForeground(new java.awt.Color(255, 255, 255));
        resetButonLogin.setText("Reset");
        resetButonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButonLoginActionPerformed(evt);
            }
        });

        loginButton.setBackground(new java.awt.Color(51, 51, 51));
        loginButton.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(253, Short.MAX_VALUE)
                        .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetButonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameFieldLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(passwordFieldLogin))))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetButonLogin)
                    .addComponent(loginButton))
                .addGap(30, 30, 30))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTER", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Impact", 3, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        passwordReg.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        passwordReg.setForeground(new java.awt.Color(255, 255, 255));
        passwordReg.setText("PASSWORD:");

        emailReg.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        emailReg.setForeground(new java.awt.Color(255, 255, 255));
        emailReg.setText("EMAIL:");

        usernameReg.setFont(new java.awt.Font("Lucida Sans", 3, 18)); // NOI18N
        usernameReg.setForeground(new java.awt.Color(255, 255, 255));
        usernameReg.setText("USERNAME:");

        emailFieldReg.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        emailFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldRegActionPerformed(evt);
            }
        });

        usernameFieldReg.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        usernameFieldReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldRegActionPerformed(evt);
            }
        });

        passwordFieldReg.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        resetButtonReg.setBackground(new java.awt.Color(0, 51, 51));
        resetButtonReg.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        resetButtonReg.setForeground(new java.awt.Color(255, 255, 255));
        resetButtonReg.setText("Reset");
        resetButtonReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonRegActionPerformed(evt);
            }
        });

        registerButton.setBackground(new java.awt.Color(0, 51, 51));
        registerButton.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Register");
        registerButton.setMaximumSize(new java.awt.Dimension(73, 23));
        registerButton.setMinimumSize(new java.awt.Dimension(73, 23));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        exitButton.setBackground(new java.awt.Color(0, 51, 51));
        exitButton.setFont(new java.awt.Font("Bahnschrift", 0, 11)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        orJustUseAsIs.setBackground(new java.awt.Color(0, 51, 51));
        orJustUseAsIs.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        orJustUseAsIs.setForeground(new java.awt.Color(255, 255, 255));
        orJustUseAsIs.setText("OR JUST USE AS IS");
        orJustUseAsIs.setActionCommand("OR JUST USE AS IS");
        orJustUseAsIs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orJustUseAsIsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(resetButtonReg, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(orJustUseAsIs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(usernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(emailReg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(passwordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(emailFieldReg, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(usernameFieldReg, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                                    .addComponent(passwordFieldReg))))))
                .addGap(30, 30, 30))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(usernameFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailFieldReg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetButtonReg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(orJustUseAsIs, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(exitButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldRegActionPerformed

    private void usernameFieldRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldRegActionPerformed

    private void usernameFieldLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldLoginActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        username = usernameFieldLogin.getText();
        password = new String(passwordFieldLogin.getPassword());

        JDBC validation = new JDBC();
        if (validation.validateCredentials(username, password)) {
            javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    Calculator mp = new Calculator();
                    mp.outputField.setText("Welcome " + username);
                    mp.setVisible(true);
                }
            });

            this.dispose();
        } 
        else {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void resetButonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButonLoginActionPerformed
        usernameFieldLogin.setText(resetMethod());
        passwordFieldLogin.setText(resetMethod());
    }//GEN-LAST:event_resetButonLoginActionPerformed

    private void resetButtonRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonRegActionPerformed
        usernameFieldReg.setText(resetMethod());
        passwordFieldReg.setText(resetMethod());
        emailFieldReg.setText(resetMethod());
    }//GEN-LAST:event_resetButtonRegActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        username = usernameFieldReg.getText();
        password = new String(passwordFieldReg.getPassword());
        email = emailFieldReg.getText();
        
        JDBC register = new JDBC();
        register.registerUser(username, password, email);
        resetButtonRegActionPerformed(evt);
    }//GEN-LAST:event_registerButtonActionPerformed

    private void orJustUseAsIsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orJustUseAsIsActionPerformed
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
                public void run() {
                    Calculator mp = new Calculator();
                    mp.outputField.setText("Welcome Person");
                    mp.setVisible(true);
                }
            });

        this.dispose();
    }//GEN-LAST:event_orJustUseAsIsActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginOrSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginOrSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailFieldReg;
    private javax.swing.JLabel emailReg;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton orJustUseAsIs;
    private javax.swing.JPasswordField passwordFieldLogin;
    private javax.swing.JPasswordField passwordFieldReg;
    private javax.swing.JLabel passwordLogin;
    private javax.swing.JLabel passwordReg;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton resetButonLogin;
    private javax.swing.JButton resetButtonReg;
    protected javax.swing.JTextField usernameFieldLogin;
    private javax.swing.JTextField usernameFieldReg;
    private javax.swing.JLabel usernameLogin;
    private javax.swing.JLabel usernameReg;
    // End of variables declaration//GEN-END:variables
}
